-- vim.api.nvim_create_autocmd({ "BufWritePre" }, {
--     pattern = { "*" },
--     callback = function()
--         -- Store fold states
--         vim.b.view = vim.fn.winsaveview()
--     end
-- })
--
-- vim.api.nvim_create_autocmd({ "BufWritePost" }, {
--     pattern = { "*" },
--     callback = function()
--         -- Restore fold states
--         if vim.b.view then
--             vim.fn.winrestview(vim.b.view)
--             vim.b.view = nil
--         end
--     end
-- })
